import { Tailor } from "@/app/types/tailor";
import { Product } from "@/app/types/product";

export const dummyTailors: Tailor[] = [
  {
    id: "1",
    userId: "user-1",
    name: "Nguyen Van Thai",
    bio: "Spezialisiert auf maßgeschneiderte Anzüge mit über 15 Jahren Erfahrung. Ich arbeite mit hochwertigen italienischen Stoffen und biete perfekte Passform.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch"],
    rating: 4.9,
    totalOrders: 287,
    yearsExperience: 15,
    specialties: ["Anzüge", "Hemden", "Hosen"],
    isVerified: true,
  },
  {
    id: "2",
    userId: "user-2",
    name: "Somchai Patel",
    bio: "Traditioneller Schneider aus Bangkok. Meine Spezialität sind elegante Hemden und Anzüge im klassischen Stil mit modernen Details.",
    country: "Thailand",
    languages: ["Thai", "Englisch"],
    rating: 4.8,
    totalOrders: 195,
    yearsExperience: 12,
    specialties: ["Hemden", "Anzüge"],
    isVerified: true,
  },
  {
    id: "3",
    userId: "user-3",
    name: "Rajesh Kumar",
    bio: "Meisterschneider aus Mumbai mit Fokus auf Hochzeitsanzüge und formelle Kleidung. Präzision und Qualität sind meine Priorität.",
    country: "Indien",
    languages: ["Hindi", "Englisch"],
    rating: 4.7,
    totalOrders: 412,
    yearsExperience: 20,
    specialties: ["Anzüge", "Brautmode", "Mäntel"],
    isVerified: true,
  },
  {
    id: "4",
    userId: "user-4",
    name: "Maria Santos",
    bio: "Spezialisiert auf Damen- und Herrenmode. Ich liebe es, klassische Schnitte mit modernen Trends zu verbinden.",
    country: "Philippinen",
    languages: ["Tagalog", "Englisch"],
    rating: 4.6,
    totalOrders: 156,
    yearsExperience: 8,
    specialties: ["Kleider", "Anzüge", "Änderungen"],
    isVerified: true,
  },
  {
    id: "5",
    userId: "user-5",
    name: "Tran Minh Duc",
    bio: "Familientradition seit drei Generationen. Spezialisiert auf Business-Anzüge und formelle Garderobe mit perfekter Passform.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch", "Französisch"],
    rating: 4.9,
    totalOrders: 523,
    yearsExperience: 25,
    specialties: ["Anzüge", "Hemden", "Mäntel"],
    isVerified: true,
  },
  {
    id: "6",
    userId: "user-6",
    name: "Ahmad Hassan",
    bio: "Moderne Schneiderei mit traditionellen Techniken. Ich biete schnelle Lieferzeiten ohne Kompromisse bei der Qualität.",
    country: "Pakistan",
    languages: ["Urdu", "Englisch"],
    rating: 4.5,
    totalOrders: 89,
    yearsExperience: 6,
    specialties: ["Anzüge", "Hemden"],
    isVerified: false,
  },
  {
    id: "7",
    userId: "user-7",
    name: "Li Wei",
    bio: "Spezialisiert auf Slim-Fit Anzüge und moderne Schnitte. Verwende ausschließlich Premium-Stoffe aus Europa.",
    country: "China",
    languages: ["Mandarin", "Englisch"],
    rating: 4.8,
    totalOrders: 234,
    yearsExperience: 11,
    specialties: ["Anzüge", "Hosen", "Maßanfertigung"],
    isVerified: true,
  },
  {
    id: "8",
    userId: "user-8",
    name: "Fatima Al-Mansour",
    bio: "Expertin für Brautmode und elegante Abendgarderobe. Jedes Stück wird mit Liebe zum Detail gefertigt.",
    country: "Vereinigte Arabische Emirate",
    languages: ["Arabisch", "Englisch"],
    rating: 4.9,
    totalOrders: 178,
    yearsExperience: 14,
    specialties: ["Brautmode", "Kleider", "Maßanfertigung"],
    isVerified: true,
  },
  {
    id: "9",
    userId: "user-9",
    name: "Carlos Mendoza",
    bio: "Schneidermeister mit Leidenschaft für perfekte Anzüge. Spezialisiert auf italienische und spanische Stile.",
    country: "Mexiko",
    languages: ["Spanisch", "Englisch"],
    rating: 4.7,
    totalOrders: 145,
    yearsExperience: 10,
    specialties: ["Anzüge", "Mäntel", "Hemden"],
    isVerified: true,
  },
  {
    id: "10",
    userId: "user-10",
    name: "Siti Nurhaliza",
    bio: "Kreative Schneiderin mit Fokus auf individuelle Anpassungen und einzigartige Designs. Schnelle und zuverlässige Arbeit.",
    country: "Malaysia",
    languages: ["Malaiisch", "Englisch"],
    rating: 4.6,
    totalOrders: 98,
    yearsExperience: 7,
    specialties: ["Kleider", "Änderungen", "Maßanfertigung"],
    isVerified: false,
  },
  {
    id: "11",
    userId: "user-11",
    name: "Pham Thanh Long",
    bio: "Spezialisiert auf Business-Hemden und formelle Kleidung. Biete kostenlose Anpassungen innerhalb von 30 Tagen.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch"],
    rating: 4.8,
    totalOrders: 267,
    yearsExperience: 13,
    specialties: ["Hemden", "Hosen", "Anzüge"],
    isVerified: true,
  },
  {
    id: "12",
    userId: "user-12",
    name: "Elena Popescu",
    bio: "Traditionelle europäische Schneiderei trifft moderne Techniken. Jedes Kleidungsstück ist ein Unikat.",
    country: "Rumänien",
    languages: ["Rumänisch", "Englisch", "Deutsch"],
    rating: 4.9,
    totalOrders: 312,
    yearsExperience: 18,
    specialties: ["Anzüge", "Mäntel", "Brautmode"],
    isVerified: true,
  },
];

export const dummyProducts: Product[] = [
  {
    id: "p1",
    tailorId: "1",
    name: "Premium Business Anzug",
    description: "Klassischer 2-teiliger Anzug aus italienischer Wolle. Perfekt für geschäftliche Anlässe. Inklusive kostenloser Änderungen.",
    price: 599,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "p2",
    tailorId: "1",
    name: "Maßgeschneidertes Hemd",
    description: "Elegantes Hemd aus ägyptischer Baumwolle. Verschiedene Farben verfügbar.",
    price: 89,
    category: "Hemd",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "p3",
    tailorId: "2",
    name: "Slim-Fit Anzug",
    description: "Moderner Slim-Fit Anzug für den zeitgemäßen Gentleman. Hochwertige Verarbeitung.",
    price: 549,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "p4",
    tailorId: "3",
    name: "Hochzeitsanzug Deluxe",
    description: "Luxuriöser 3-teiliger Hochzeitsanzug mit Weste. Perfekt für den großen Tag.",
    price: 899,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "p5",
    tailorId: "3",
    name: "Winter Mantel",
    description: "Eleganter Wollmantel für die kalte Jahreszeit. Zeitloses Design.",
    price: 449,
    category: "Mantel",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "p6",
    tailorId: "4",
    name: "Cocktailkleid",
    description: "Elegantes Cocktailkleid für besondere Anlässe. Individuelle Anpassung möglich.",
    price: 299,
    category: "Kleid",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "p7",
    tailorId: "5",
    name: "Executive Anzug",
    description: "Premium Anzug für Führungskräfte. Aus feinster Schurwolle gefertigt.",
    price: 799,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "p8",
    tailorId: "5",
    name: "Business Hemd Paket",
    description: "Set aus 3 maßgeschneiderten Business-Hemden. Verschiedene Muster.",
    price: 199,
    category: "Hemd",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "p9",
    tailorId: "7",
    name: "Modern Fit Anzug",
    description: "Zeitgemäßer Anzug mit modernem Schnitt. Ideal für junge Professionals.",
    price: 499,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-30"),
  },
  {
    id: "p10",
    tailorId: "8",
    name: "Brautkleid Classic",
    description: "Traumhaftes Brautkleid in klassischem Stil. Vollständig anpassbar.",
    price: 1299,
    category: "Kleid",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "p11",
    tailorId: "9",
    name: "Italienischer Anzug",
    description: "Anzug im italienischen Stil mit perfekter Passform. Premium Qualität.",
    price: 699,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "p12",
    tailorId: "11",
    name: "Business Hose",
    description: "Klassische Business-Hose aus hochwertiger Wolle. Perfekte Passform garantiert.",
    price: 129,
    category: "Hose",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "p13",
    tailorId: "12",
    name: "Smoking",
    description: "Eleganter Smoking für formelle Anlässe. Inklusive Fliege und Einstecktuch.",
    price: 849,
    category: "Anzug",
    imageUrl: null,
    featured: true,
    createdAt: new Date("2024-01-08"),
  },
  {
    id: "p14",
    tailorId: "12",
    name: "Herbst Mantel",
    description: "Stilvoller Mantel für Herbst und Frühling. Wasserabweisend behandelt.",
    price: 399,
    category: "Mantel",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-12"),
  },
  {
    id: "p15",
    tailorId: "7",
    name: "Chino Hose",
    description: "Lässige Chino-Hose für Business Casual. Mehrere Farben verfügbar.",
    price: 99,
    category: "Hose",
    imageUrl: null,
    featured: false,
    createdAt: new Date("2024-02-18"),
  },
];
