import { Tailor } from "@/app/types/tailor";

export const dummyTailors: Tailor[] = [
  {
    id: "1",
    userId: "user-1",
    name: "Nguyen Van Thai",
    bio: "Spezialisiert auf maßgeschneiderte Anzüge mit über 15 Jahren Erfahrung. Ich arbeite mit hochwertigen italienischen Stoffen und biete perfekte Passform.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch"],
    rating: 4.9,
    totalOrders: 287,
    yearsExperience: 15,
    specialties: ["Anzüge", "Hemden", "Hosen"],
    isVerified: true,
  },
  {
    id: "2",
    userId: "user-2",
    name: "Somchai Patel",
    bio: "Traditioneller Schneider aus Bangkok. Meine Spezialität sind elegante Hemden und Anzüge im klassischen Stil mit modernen Details.",
    country: "Thailand",
    languages: ["Thai", "Englisch"],
    rating: 4.8,
    totalOrders: 195,
    yearsExperience: 12,
    specialties: ["Hemden", "Anzüge"],
    isVerified: true,
  },
  {
    id: "3",
    userId: "user-3",
    name: "Rajesh Kumar",
    bio: "Meisterschneider aus Mumbai mit Fokus auf Hochzeitsanzüge und formelle Kleidung. Präzision und Qualität sind meine Priorität.",
    country: "Indien",
    languages: ["Hindi", "Englisch"],
    rating: 4.7,
    totalOrders: 412,
    yearsExperience: 20,
    specialties: ["Anzüge", "Brautmode", "Mäntel"],
    isVerified: true,
  },
  {
    id: "4",
    userId: "user-4",
    name: "Maria Santos",
    bio: "Spezialisiert auf Damen- und Herrenmode. Ich liebe es, klassische Schnitte mit modernen Trends zu verbinden.",
    country: "Philippinen",
    languages: ["Tagalog", "Englisch"],
    rating: 4.6,
    totalOrders: 156,
    yearsExperience: 8,
    specialties: ["Kleider", "Anzüge", "Änderungen"],
    isVerified: true,
  },
  {
    id: "5",
    userId: "user-5",
    name: "Tran Minh Duc",
    bio: "Familientradition seit drei Generationen. Spezialisiert auf Business-Anzüge und formelle Garderobe mit perfekter Passform.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch", "Französisch"],
    rating: 4.9,
    totalOrders: 523,
    yearsExperience: 25,
    specialties: ["Anzüge", "Hemden", "Mäntel"],
    isVerified: true,
  },
  {
    id: "6",
    userId: "user-6",
    name: "Ahmad Hassan",
    bio: "Moderne Schneiderei mit traditionellen Techniken. Ich biete schnelle Lieferzeiten ohne Kompromisse bei der Qualität.",
    country: "Pakistan",
    languages: ["Urdu", "Englisch"],
    rating: 4.5,
    totalOrders: 89,
    yearsExperience: 6,
    specialties: ["Anzüge", "Hemden"],
    isVerified: false,
  },
  {
    id: "7",
    userId: "user-7",
    name: "Li Wei",
    bio: "Spezialisiert auf Slim-Fit Anzüge und moderne Schnitte. Verwende ausschließlich Premium-Stoffe aus Europa.",
    country: "China",
    languages: ["Mandarin", "Englisch"],
    rating: 4.8,
    totalOrders: 234,
    yearsExperience: 11,
    specialties: ["Anzüge", "Hosen", "Maßanfertigung"],
    isVerified: true,
  },
  {
    id: "8",
    userId: "user-8",
    name: "Fatima Al-Mansour",
    bio: "Expertin für Brautmode und elegante Abendgarderobe. Jedes Stück wird mit Liebe zum Detail gefertigt.",
    country: "Vereinigte Arabische Emirate",
    languages: ["Arabisch", "Englisch"],
    rating: 4.9,
    totalOrders: 178,
    yearsExperience: 14,
    specialties: ["Brautmode", "Kleider", "Maßanfertigung"],
    isVerified: true,
  },
  {
    id: "9",
    userId: "user-9",
    name: "Carlos Mendoza",
    bio: "Schneidermeister mit Leidenschaft für perfekte Anzüge. Spezialisiert auf italienische und spanische Stile.",
    country: "Mexiko",
    languages: ["Spanisch", "Englisch"],
    rating: 4.7,
    totalOrders: 145,
    yearsExperience: 10,
    specialties: ["Anzüge", "Mäntel", "Hemden"],
    isVerified: true,
  },
  {
    id: "10",
    userId: "user-10",
    name: "Siti Nurhaliza",
    bio: "Kreative Schneiderin mit Fokus auf individuelle Anpassungen und einzigartige Designs. Schnelle und zuverlässige Arbeit.",
    country: "Malaysia",
    languages: ["Malaiisch", "Englisch"],
    rating: 4.6,
    totalOrders: 98,
    yearsExperience: 7,
    specialties: ["Kleider", "Änderungen", "Maßanfertigung"],
    isVerified: false,
  },
  {
    id: "11",
    userId: "user-11",
    name: "Pham Thanh Long",
    bio: "Spezialisiert auf Business-Hemden und formelle Kleidung. Biete kostenlose Anpassungen innerhalb von 30 Tagen.",
    country: "Vietnam",
    languages: ["Vietnamesisch", "Englisch"],
    rating: 4.8,
    totalOrders: 267,
    yearsExperience: 13,
    specialties: ["Hemden", "Hosen", "Anzüge"],
    isVerified: true,
  },
  {
    id: "12",
    userId: "user-12",
    name: "Elena Popescu",
    bio: "Traditionelle europäische Schneiderei trifft moderne Techniken. Jedes Kleidungsstück ist ein Unikat.",
    country: "Rumänien",
    languages: ["Rumänisch", "Englisch", "Deutsch"],
    rating: 4.9,
    totalOrders: 312,
    yearsExperience: 18,
    specialties: ["Anzüge", "Mäntel", "Brautmode"],
    isVerified: true,
  },
];
